on:
    push:
        branches:
            - "master"
            - "main"

jobs:
    run_and_test:
        runs-on: "ubuntu-latest"
        
        steps:
            - uses: actions/checkout@v4

            - name: "Install UV"
              uses: astral-sh/setup-uv@v7

            - name: "Setup Python"
              run: uv python install 3.14.4

            - name: "Install dependencies"
              run: uv sync --dev

            - name: "Run Ruff checks"
              run: uv run ruff check --show-fixes

            - name: "Run Ruff formatting"
              run: uv run ruff format --check

            - name: "Run Pytest tests"
              run: uv run pytest
