on:
    push:
        branches:
            - "master"
            - "main"

jobs:
    run_and_test:
        runs-on: "ubuntu-latest"
        
        steps:
            - uses: actions/checkout@v4

            - name: "Install uv"
              uses: astral-sh/setup-uv@v7
              with:
                enable-cache: true
                cache-local-path: "**/.uv_cache"
                python-version: '3.14.5'

            - name: "Install dependencies"
              run: uv sync --frozen

            - name: "Run Ruff checker"
              run: uv run ruff check --show-fixes

            - name: "Run Ruff linter"
              run: uv run ruff format --check

            - name: "Run Pytest"
              run: uv run pytest --tb=short --cov

            - name: "Collect coverage report"
              run: uv run pytest --cov --cov-report json

            - name: "Process report"
              run: |
                honk parse -p coverage.json -t "files/*/summary" map-map --header "files" --excluded-col "*_display" > $GITHUB_STEP_SUMMARY
                honk parse -p coverage.json -t "files/*" group -i "missing_lines" -i "excluded_lines" | honk parse -m json map-map --header "files" > $GITHUB_STEP_SUMMARY